name: Build Godot Engine

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          brew install scons
          pip install -r requirements.txt

      - name: Run build script
        run: bash build-skillcap.sh

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: godot-engine
          path: ./build/Godot\ Skillcap.app
